-- Stores the public dashboard dataset generated by the weekly refresh.
-- The frontend reads this snapshot instead of triggering expensive live searches.

CREATE TABLE IF NOT EXISTS public.dashboard_snapshots (
  id text PRIMARY KEY DEFAULT 'latest',
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  source text NOT NULL DEFAULT 'manual',
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.dashboard_refresh_runs
  ADD COLUMN IF NOT EXISTS data_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE public.dashboard_snapshots ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read active dashboard snapshots" ON public.dashboard_snapshots;
CREATE POLICY "Public can read active dashboard snapshots"
ON public.dashboard_snapshots
FOR SELECT
USING (status = 'active');

DROP POLICY IF EXISTS "Menatech admins can manage dashboard snapshots" ON public.dashboard_snapshots;
CREATE POLICY "Menatech admins can manage dashboard snapshots"
ON public.dashboard_snapshots
FOR ALL
USING (public.is_menatech_admin())
WITH CHECK (public.is_menatech_admin());

CREATE INDEX IF NOT EXISTS dashboard_snapshots_status_updated_at_idx
  ON public.dashboard_snapshots (status, updated_at DESC);
