// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzkyzfwqjiskwnnapiin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6a3l6Zndxamlza3dubmFwaWluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTk5MTcsImV4cCI6MjA2NTQ5NTkxN30.Or_iCbPzn8NB9Tu9J8OygIpEKvKIpzAO5rmJxRonNGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);